---
title: 'Proceso Cientista: Modelagem'
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

## Carregando os pacotes que serão utilizados

```{r loadlibs, results='hide', message=F, warning=F}
library(dplyr)
library(recipes)
library(rsample)
library(yardstick)
library(FFTrees)
```

## Carregando a base de dados

```{r load data}
source('r_functions/load_rain_dataset.R')
rain <- load_rain_dataset()
rain$target <- recode(rain$raintomorrow, Yes = 1, No = 0)
```

```{r}
set.seed(42)
split <- initial_split(rain, 0.5, "target")
training <- training(split)
testing <- testing(split)
```


```{r rain_recipe}
rain_recipe <-
  recipe(
    target ~ location
    + mintemp
    + maxtemp
    + raintoday
    + temp
    + humidity,
    data = training
  ) %>%
  check_cols(all_predictors()) %>%
  step_medianimpute(mintemp, maxtemp, temp, humidity) %>%
  step_modeimpute(location, raintoday) %>%
  prep()

saveRDS(rain_recipe, "modelling/rain_recipe.RDS")
```


```{r}
training_baked <- juice(rain_recipe)

set.seed(42)
rain_fft <- 
  FFTrees(target ~ .,
          data = training_baked,
          main = "Will it rain tomorrow?",
          decision.labels = c("Bring sunscreen", "Bring umbrella"))

# saveRDS(rain_fft, 'modelling/rain_fft.RDS')
```





