---
title: 'Proceso Cientista: Modelagem'
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

## Carregando os pacotes que serão utilizados

```{r loadlibs, results='hide', message=F, warning=F}
library(dplyr)
library(recipes)
library(caret)
```

## Carregando a base de dados

```{r load data}
source('r_functions/load_rain_dataset.R')
rain <- load_rain_dataset()
```

```{r}
set.seed(42)
inTrain <- createDataPartition(rain$raintomorrow, p=0.7, list=FALSE)
training <- rain[inTrain,]
testing <- rain[-inTrain,]
```


```{r rain_recipe}
rain_recipe <-
  recipe(
    raintomorrow ~ .,
    data = training
  ) %>%
  step_mutate(
    tempamplitude = maxtemp - mintemp,
    humiditychange = humidity3pm - humidity9am,
    pressurechange = pressure3pm - pressure9am
  ) %>%
  step_rm(cloud9am, cloud3pm, sunshine, evaporation,
         amountOfRain, date) %>% 
  step_corr(all_numeric()) %>% 
  step_nzv(-all_outcomes()) %>% 
  step_medianimpute(all_numeric()) %>% 
  step_modeimpute(all_nominal()) %>% 
  prep()
```


```{r}
training_baked <- juice(rain_recipe)
```

```{r}
train.control <- trainControl(
  method = "cv",
  number = 5,
  verboseIter = TRUE,
  summaryFunction = twoClassSummary,
  classProbs = TRUE
)
# https://csantill.github.io/RTuningModelParameters/
```

```{r}
set.seed(42)
rpart1 <- train(raintomorrow ~ .,
                data = training_baked,
                method = "rpart",
                na.action = na.pass,
                trControl = train.control)
saveRDS(rpar1, "modelling/rpart1.RDS")
```



